name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build project (if applicable)
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist  # Change this to your build output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

